Check [WILDCARD]/test/exit_sanitizer.ts
running 3 tests from [WILDCARD]/test/exit_sanitizer.ts
test exit(0) ... FAILED ([WILDCARD])
test exit(1) ... FAILED ([WILDCARD])
test exit(2) ... FAILED ([WILDCARD])

failures:

exit(0)
AssertionError: Test case attempted to exit with exit code: 0
    at assert (deno:runtime/js/06_util.js:36:13)
    at deno:runtime/js/40_testing.js:92:9
    at Object.exit (deno:runtime/js/30_os.js:52:7)
    at [WILDCARD]/test/exit_sanitizer.ts:2:8
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:35:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:72:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:99:15)
    at runTest (deno:runtime/js/40_testing.js:218:13)
    at Object.runTests (deno:runtime/js/40_testing.js:264:13)
    at [WILDCARD]/$deno$test.js:1:27

exit(1)
AssertionError: Test case attempted to exit with exit code: 1
    at assert (deno:runtime/js/06_util.js:36:13)
    at deno:runtime/js/40_testing.js:92:9
    at Object.exit (deno:runtime/js/30_os.js:52:7)
    at [WILDCARD]/test/exit_sanitizer.ts:6:8
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:35:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:72:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:99:15)
    at runTest (deno:runtime/js/40_testing.js:218:13)
    at Object.runTests (deno:runtime/js/40_testing.js:264:13)
    at async [WILDCARD]/$deno$test.js:1:1

exit(2)
AssertionError: Test case attempted to exit with exit code: 2
    at assert (deno:runtime/js/06_util.js:36:13)
    at deno:runtime/js/40_testing.js:92:9
    at Object.exit (deno:runtime/js/30_os.js:52:7)
    at [WILDCARD]/test/exit_sanitizer.ts:10:8
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:35:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:72:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:99:15)
    at runTest (deno:runtime/js/40_testing.js:218:13)
    at Object.runTests (deno:runtime/js/40_testing.js:264:13)
    at async [WILDCARD]/$deno$test.js:1:1

failures:

	exit(0)
	exit(1)
	exit(2)

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out ([WILDCARD])

